### ISSUE TITLE
Differences between cocos and cupy?

### ISSUE THREAD

**Issue by StanczakDominik** [michaelnowotny/cocos#1]
I guess this is not much of an actual issue (except maybe it could result in an added paragraph in the README!), but I didn't see any better place of asking this. How does `cocos` relate to the [`cupy`](https://github.com/cupy/cupy) project? Are there any major paradigm or performance differences?

**Comment by michaelnowotny** [comment]
Hi Dominik,

this is a good question. 

I think one of the main differences is that cupy runs on CUDA while ArrayFire, which Cocos is based on supports both CUDA and OpenCL. For the last few years, Apple computers have only been available with AMD GPUs (these only support OpenCL but not CUDA). So Cocos code runs on both NVidia and AMD GPUs.

Another difference seems to be that cupy allows for the integration of user-defined GPU kernels.  ArrayFire supports custom CUDA and OpenCL kernels (https://arrayfire.com/arrayfire-cuda-interoperability/, https://arrayfire.com/arrayfire-opencl-interoperability/). It would be interesting to see how this functionality can be brought to into Cocos.

I had thought about adding a benchmark section to compare Cocos to various alternatives such as native ArrayFire on C++, CUDA via Numba, etc. A comparison with Cupy could naturally go there as well.

Since I am primarily working on MacOS, I am not very familiar with cupy. It seems that you have extensive experience in high performance/GPU computing. Would you be interested in helping to compile a list of differences with cupy and perhaps other alternatives?

Thank you,

Michael

**Comment by michaelnowotny** [comment]
A benchmark comparing NumPy, Cocos, and CuPy has been added.
